name: Telegram Quiz Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run the script
      env:
        WP_URL: ${{ secrets.WP_URL }}
        WP_USER: ${{ secrets.WP_USER }}
        WP_PASS: ${{ secrets.WP_PASS }}
        PROMO_MESSAGE: ${{ secrets.PROMO_MESSAGE }}
        telegram_bot_token: ${{ secrets.telegram_bot_token }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
      run: |
        python main.py
